spring:
  r2dbc:
    username: postgres
    password: 123
    url: r2dbc:postgresql://localhost:5432/evianda
  flyway:
    url: jdbc:postgresql://localhost:5432/evianda
    locations: classpath:db/migration